### PR TITLE
eitherGTop and eitherGBottom for Bounded

### PR DESCRIPTION
**Pull request by zudov**
It's not obvious if we should add it on not.

I'll add docs if we decide to merge it in.

Not quite sure about the names perhaps `gBottomEither`/`gTopEither` is better.

### CODE REVIEW

**Comment by garyb** [comment]
I like the idea, in fact in a similar way we could probably derive `Enum` as a whole, but I think having the `Either` in there limits the usefulness - how would you actually use it to define a `Bounded` instance? (I do see why it's required, just thinking aloud).

**Comment by paf31** [comment]
I feel like `Enum` would be easier depending on how you define it: if you mean "finite" ,then obviously `Array` fails, but if you mean "enumerable" then you can make pretty much any `Generic` thing an instance of `Enum`. `Bounded` is more tricky as this PR shows, and I wonder if it's simpler to just write down two values by hand than reason about whether it's possible to write them down. Type classes give us the ability to reason about existence of structures by looking at types, and approximations like this necessarily remove that ability. I don't think this is _bad_ code, but maybe it belongs in an `Unsafe` module, in which case, we'd be free to just drop the `Either`.

**Comment by garyb** [comment]
Our `Enum` is `Bounded`, it's intended for "small" (or at least finite types) so it has the same problem.

**Comment by paf31** [comment]
I'd argue that "enumerable" is a more useful abstraction. I'd be interested in revising `Enum` to refine it to `Enumerable` and `Finite`.

**Comment by garyb** [comment]
Maybe we could have `Enumerable` and `Enum`, `Enum` for bounded small types because it's a small word :wink:

**Comment by zudov** [comment]
@garyb We can't write `gTop :: forall a. (Generic a) => a -> a`, since many Generic ADTs are not Bounded. Having partial function in a library is not good, so we defer the decision of what to do when the ADT is not Bounded to the user. The user can make sure that his ADT is in fact Bounded and then use `fromRight` in order to define an instance.

**Comment by paf31** [comment]
I guess the question is: when is this useful? If it's only for writing instances, you _know_ if the type is bounded or not. If not, you have to decide if you would ever use it generically or not.

**Comment by gbaz** [comment]
One thought -- add a Finite class with no methods, and have gTop and gBottom require that constraint. That way, it forces the user to make their datatype an instance of Finite and "promise" the size before the method can be invoked.

**Comment by zudov** [comment]
@gbaz But we would still have to fail at runtime if the ADT isn't actually Finite and Bounded. And I am not sure if it makes UX better. Normally you have to make sure that you ADT is Bounded and then put
```haskell
instance myADTBounded :: Bounded MyADT where
  ...
```
But with `Finite` you would still have to make sure that your ADT is `Bounded`, and then just put yet another line

```haskell
instance MyADTFinite :: Finite MyADT
instance myADTBounded :: Bounded MyADT where
```
And the thing would still fail if `MyADT` isn't in fact Bounded

**Comment by paf31** [comment]
I'd like to come back to this once we start using `generics-rep` a bit more.

**Comment by paf31** [comment]
I think we should consider moving this to `generics-rep` for the reasons explained above.

**Pull request closed without merging**
