### PR TITLE
Fix #7

### LINKED ISSUE #7: Add SigBoolean and SBoolean?

### PR DESCRIPTION
**Pull request by paf31**
@gbaz I had a fix ready to go anyway, so it's here, depending on what we decide.

### CODE REVIEW

**Comment by paf31** [comment]
@gbaz Actually, could you please review this? It's fiddly enough that I think it warrants a second pair of eyes on it.

**Comment by paf31** [comment]
@gbaz So is this good to merge? I just wanted to make sure I had the `Ord` instance right. Thanks.

**Comment by gbaz** [comment]
just reviewed, lgtm

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
